added spec for sessions controller, but the use of .permit in the strong_params method is causing the specs to fail due to NoMethodError: undefined method 'permit' for string. Researched for about 30 mins, no clear path to fixing this error currently so moving on to write other tests